name: axia_works_youtube
description: A new Flutter application.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  badges: ^1.2.0
  freezed_annotation: ^0.11.0
  retrofit: ^1.3.4
  logging: ^0.11.4
  pretty_dio_logger: ^1.1.1
  flutter_riverpod: ^0.12.1
  flutter_state_notifier: ^0.6.1
  shared_preferences: ^0.5.12+4
  moor: ^3.4.0
  sqlite3_flutter_libs: ^0.4.0
  path_provider: ^1.6.28
  path: ^1.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.10.0
  freezed: ^0.11.2
  retrofit_generator: ^1.4.1
  json_serializable: ^3.3.0
  moor_generator: ^3.3.1

flutter:
  uses-material-design: true
  assets:
    - images/

